### ISSUE TITLE
license & description

### ISSUE THREAD

**Issue by IzzySoft** [lyx1920055799/NextEditor#1]
Thanks for your open-source app! Just wondering:

* what license did you choose? Not specifying any means "all rights reserved" (i.e. "not free"), which might scare some folks away
* is there any description of the app's features, to attract users?
* some screenshots might be nice, too :wink:

**Comment by lyx1920055799** [comment]
> Thanks for your open-source app! Just wondering:
> 
> * what license did you choose? Not specifying any means "all rights reserved" (i.e. "not free"), which might scare some folks away
> * is there any description of the app's features, to attract users?
> * some screenshots might be nice, too 😉

Thanks for your suggestions, I tried to add those things.

**Comment by lyx1920055799** [comment]
I also know that it does not affect the code, just the application metadata, but I still like to keep the structure simple for the future.

**Comment by IzzySoft** [comment]
As you wish; I'll then drop the source of that PR.
