### ISSUE TITLE
Feature request / 功能要求

### ISSUE THREAD

**Issue by Mokura** [lyx1920055799/NextEditor#3]
I apologize if the Chinese is bad, I am using Google Translate.

如果中文不好，我很抱歉，我正在使用Google翻译。

An option for dark mode and monospaced fonts would be very useful.  Thank you.

深色模式和等宽字体的选项将非常有用。 谢谢你。

**Comment by lyx1920055799** [comment]
Thanks, this is a nice feature, I will try to add it in the future. My English is not good, but I also use Google Translate.
